# ESLint 파서 설정
# @babel/eslint-parser를 사용하여 실험적인 JavaScript 문법(예: 클래스 필드)을 지원
parser: '@babel/eslint-parser'

# ECMAScript 버전과 모듈 사용 설정
parserOptions:
  # async와 await 키워드를 사용하려면 ECMAScript 버전을 2017 이상으로 설정
  # 클래스 필드 같은 실험적인 JavaScript 문법을 사용하려면 ECMAScript 버전을 2021로 설정
  ecmaVersion: 2021

  # import와 export 구문을 사용하려면 sourceType을 module로 설정
  sourceType: 'module'

  # @babel/eslint-parser를 사용하려면 requireConfigFile을 false로 설정
  # 이 설정은 Babel 설정 파일 없이 @babel/eslint-parser를 사용할 수 있게 함
  requireConfigFile: false

# ESLint 규칙 설정
rules:
  # 재할당되지 않는 모든 let 변수를 오류로 표시
  prefer-const: 'error'

  # 사용되지 않는 변수를 오류로 표시. 단, '_'로 시작하는 변수는 무시
  no-unused-vars: ["error", { "argsIgnorePattern": "^_" }]
